import Head from "next/head";
import Card from "../components/Card";
import Category from "../components/Category";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import NextTrip from "../components/NextTrip";
import Partners from "../components/Partners";
import Search from "../components/Search";
import Subscribe from "../components/Subscribe";
import Testimonial from "../components/Testimonial";
// import imagae from "../public/assets/Bg.png"
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>WindTravels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex absolute mb-10 max-w-fit sm:w-full shadow-xl shadow-[#E7AC72]">
      <img src="assets/Bg.png" alt=""  className="w-[900px] h-[900px] object-cover object-center -mr-24"/>
      <img src="/assets/Boat.png" alt="" className="w-[620px] h-[900px] "/>
      </div>
      <Hero />
      <div className="mt-12 relative">
        <h1 className="text-center text-lg font-semibold">CATEGORY</h1>
        <h1 className="text-center text-5xl text-[#14183E] font-bold">
          We Offer Best Services
        </h1>
        <img src="/assets/plus.png" alt="" className="absolute top-0 right-0"/>
        <div className="flex my-[100px] justify-evenly items-center">
          <Category
            icon= "/assets/antina.png"
            title="Calculated Weather"
            desc={`The color of the It supports both default and colors color of the component,`}
          />
          <Category
            icon="/assets/plane-with-cube2.png"
            title="Calculated Weather"
            desc={`The color of the component. It default and custom theme colors,`}
          />
          <Category
           icon= "/assets/mic.png"
            title="Calculated Weather"
            desc={`The color of the component. It supports both custom theme colors,`}
          />
          <Category
           icon= "/assets/setting.png"
            title="Calculated Weather"
            desc={`The color of the component. It supports both default and custom theme colors,`}
          />
        </div>
      </div>
      <h4 className="text-center">Top Selling </h4>
      <h1 className="text-center">Top Destinations</h1>
      <div className="flex justify-center bg-orange-300">
        <Card />
        <Card />
        <Card />
      </div>
      <div>
        <NextTrip />
      </div>
      <Testimonial />
      <h1 className="ml-10 text-2xl font-bold">Trusted By Companies</h1>
      <Partners />
      <Subscribe />
      <Footer />
    </div>
  );
}
