import Head from "next/head";
import { Fade } from "react-reveal";
import Jump from 'react-reveal/Jump';
import Card from "../components/Card";
import RubberBand from 'react-reveal/RubberBand';
import Category from "../components/Category";
import Destinaion from "../components/Destination";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import NextTrip from "../components/NextTrip";
import Partners from "../components/Partners";
import Search from "../components/Search";
import Subscribe from "../components/Subscribe";
import Testimonial from "../components/Testimonial";
import Pulse from 'react-reveal/Pulse';
import Flash from 'react-reveal/Flash';

// import imagae from "../public/assets/Bg.png"
export default function Home() {
  return (
    <div className="">
      <Head>
        <title>WindTravels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fade>
      <div className="flex bg-[#E5E5E5] absolute mb-10 max-w-fit sm:w-full shadow-xl shadow-[#E7AC72] lg:w-[100vw]">
        <img
          src="assets/Bg.png" alt=" "
         
          className="w-[60vw] h-[900px] object-cover object-center -mr-24 lg:w-[60vw] md:w-[100vw] sm:w-[100vw]"
        />
        <img src="/assets/Boat.png" className="w-[47vw] h-[900px] lg:w-[47vw] md:invisible sm:invisible lg:visible xl:visible 2xl:visible" alt=""/>
      </div>
      </Fade>
      <Hero />
      <div className="mt-12 relative">
  
        <h1 className="text-center text-lg font-semibold xl:mt-28 xl:mb-5 lg:mt-24 lg:mb-4">CATEGORY</h1>
<RubberBand>
        <h1 className="text-center text-5xl text-[#14183E] font-bold font-volk sm:text-[35px]">
          We Offer Best Services
        </h1>
        </RubberBand>
        <img src="/assets/plus.png" alt="" className="absolute top-0 right-0 sm:top-[-10px] sm:right-[25px] xl:top-[-15px] xl:right-[10px] lg:right-[0px]  animate-pulse" />
        <div className="flex my-[100px] justify-between items-center flex-wrap xl:justify-evenly lg:justify-evenly md:justify-evenly">
          <Category
            icon="/assets/antina.png"
            title="Calculated Weather"
            desc={`The color of the It supports both default and colors color of the component,`}
          />
          <Category
            icon="/assets/plane-with-cube2.png"
            title="Calculated Weather"
            desc={`The color of the component. It default and custom theme colors,`}
          />
          <Category
            icon="/assets/mic.png"
            title="Calculated Weather"
            desc={`The color of the component. It supports both custom theme colors,`}
          />
          <Category
            icon="/assets/setting.png"
            title="Calculated Weather"
            desc={`The color of the component. It supports both default and custom theme colors,`}
          />
        </div>
      </div>
      <h4 className="text-center font-semibold text-lg lg:mb-4">Top Selling </h4>
      <Jump delay={500}>
      <h1 className="text-center text-5xl font-bold font-volk sm:text-[35px]">Top Destinations</h1>
      </Jump>
      <div className="flex justify-evenly bg-white  my-16 relative">
      <Flash count={0.5}>
        <Destinaion
          img="/assets/des1Edit.png"
          title="Cebu,Phillipines"
          price="$1.2k"
          svg={
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5 rotate-45"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
            </svg>
          }
          days="10 Days Trip"
        />
        </Flash>
        <Flash delay={80} count={0.5}>
        <Destinaion
          img="/assets/des2Edit.jpg"
          title="Manila,Phillipines"
          price="$2.3k"
          svg={
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-5 rotate-45"
              viewBox="0 0 20 20"
              fill="currentColor"
            >
              <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
            </svg>
          }
          days="15 Days Trip"
        />
        </Flash>
        <Flash count={0.5} delay={160}>
        <Destinaion
          img="/assets/des3Edit.png"
          title="Davao,Phillipines"
          price="$3.2k"
          svg={
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5 rotate-45"
              viewBox="0 0 20 20 "
              fill="currentColor"
            >
              <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
            </svg>
          }
          days="$20 Days Trip"
        />
        </Flash>
      </div>
      <div className="relative">
        {" "}
        <img
          src="/assets/Decore.png"
          alt=""
          className="absolute right-14 z-10 -top-[330px] xl:right-12 xl:-top-[370px] lg:right-4 lg:-top-[370px] animate-pulse"
        />
      </div>

      <div>
        <NextTrip />
      </div>
      <Testimonial />
      <Pulse>
      <h1 className="ml-20 text-[51px] font-bold text-[#14183E] mt-24  sm:text-[35px] sm:ml-10 font-volk xl:ml-20">Trusted By Companies</h1>
      </Pulse>
      <Partners />
      <Subscribe />
      <Footer />
    </div>
  );
}
