import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>WindTravels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className="bg-[url('../assets/travel-bg-img.png')] bg-cover object-contain h-96 bg-center bg-no-repeat">

<h1>image is not showing</h1>
</div>
    </div>
  )
}
